// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://wborcnalsyekzwbtmoos.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Indib3JjbmFsc3lla3p3YnRtb29zIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDY5Mjc0NzMsImV4cCI6MjA2MjUwMzQ3M30.mjZuTpeSd1Hr4Gxj-b7fqpTI1FfoKiUJQ95rnD6TjNo";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);